added DCDC status CAN message when DCDC state changes
UWaterloo-Formula-Electric/firmware pull request #17
Opened 2023-11-15 09:39 UTC by HappyRedMapleLeaf

Literally added one line of code. Calls sendCAN_PDU_DCDC_Status() when DCDC switches on -> off or off -> on. Accidentally added some newlines as well.

2023-11-16 22:28 UTC, addison-ch approved these changes

2023-11-16 23:28 UTC, DanBishara approved these changes

2023-11-16 23:28 UTC, DanBishara commented on pdu/Src/LTC4110.c
> +}
Red circle means add a line at the end of the file

2023-11-16 23:48 UTC, aryanGajelli reviewed
Remove the newlines to try and keep as much of the orginal formatting. Once that is done it LGTM for approval

2023-11-16 23:48 UTC, aryanGajelli commented on pdu/Src/LTC4110.c
> +
nit: remove newline

2023-11-16 23:48 UTC, aryanGajelli commented on pdu/Src/LTC4110.c
> +
nit: remove newline

2023-11-16 23:48 UTC, aryanGajelli commented on pdu/Src/LTC4110.c
> +
nit: remove newline

2023-11-18 02:46 UTC, aryanGajelli requested changes
Change target to merge into develop

2023-11-20 04:19 UTC, aryanGajelli approved these changes

2023-11-20 04:59 UTC, merged