Post Hybrid
UWaterloo-Formula-Electric/firmware pull request #30
Opened 2024-05-15 23:32 UTC by Justin-Vuong

2024-05-23 17:15 UTC, jlim25 reviewed
Left some feedback and questions

2024-05-23 17:15 UTC, jlim25 commented on vcu/Src/drive_by_wire.c
> +    // } else if (!(brakePressure > MIN_BRAKE_PRESSURE)) {
This is commented out because of the brake fluid issue at comp right? Did we resolve that issue?

2024-05-24 04:59 UTC, addison-ch requested changes

2024-05-24 04:59 UTC, addison-ch commented on pdu/Src/controlStateMachine_mock.c
> +    fsmSendEvent(&mainFsmHandle, EV_EM_Enable, portMAX_DELAY);
If you transition to EM Enable right after faking the temperature, thats just going to turn the MC on and overwrite that with the real temperature readings isn't it?

2024-05-24 04:59 UTC, addison-ch commented on vcu/Src/drive_by_wire.c
> +            }
missing break :(

i thought this was fixed?

2024-09-06 22:56 UTC, aryanGajelli approved these changes
This is a lot of changes, I'll give it a stamp for now as nothing looks broken to me from a quick glance

2024-10-06 17:42 UTC, DanBishara approved these changes

2024-10-06 17:45 UTC, merged